### ISSUE TITLE
PORO's instead of Draper

### ISSUE THREAD

**Issue by leesmith** [CodeRocketCo/enhanced-rails-architecture#2]
I'm not saying there's a right way and a wrong way to use presenters ("decorators"), but I thought I'd drop a link to an illustration on how to accomplish this design pattern without a gem (Draper). I thought these were some really good points being made and I'm all about minimizing the amount of gems I use in a project. Nice work on your list!

https://thepugautomatic.com/2014/03/draper/

**Comment by JiProchazka** [comment]
Added in last commit. Thanks

**Comment by leesmith** [comment]
PORO's FTW! 👍

**Comment by sneakernets** [comment]
I don't want to provoke anything but: is there *still* contention with with PORO's vs something like Draper? My opinion is with the "as few gems as possible" crowd, and if that technically means "logic" in the view, then, so what? It's not like we're _not already doing that_ with Javascript. 🤔
